/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica5_rgb;

/**
 *
 * @author Usuario
 */
public class FiltrosRGB extends javax.swing.JFrame {

    /**
     * Creates new form FiltrosRGB
     */
    public FiltrosRGB() {
        initComponents();
        setLocationRelativeTo(null);
        lienzo1.setRed(rojobox.isSelected());
        lienzo1.setGreen(verdebox.isSelected());
        lienzo1.setBlue(azulbox.isSelected());
        lienzo1.setPosxLogo(582);
        lienzo1.setPosyLogo(-25);
        lienzo1.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoposicion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rojobox = new javax.swing.JCheckBox();
        verdebox = new javax.swing.JCheckBox();
        azulbox = new javax.swing.JCheckBox();
        todos = new javax.swing.JCheckBox();
        textcanales = new javax.swing.JLabel();
        textposicion = new javax.swing.JLabel();
        inferiorderecha = new javax.swing.JRadioButton();
        inferiorizquierda = new javax.swing.JRadioButton();
        superiorizquierda = new javax.swing.JRadioButton();
        superiorderecha = new javax.swing.JRadioButton();
        lienzo1 = new com.mycompany.practica5_rgb.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rojobox.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        rojobox.setForeground(new java.awt.Color(255, 255, 255));
        rojobox.setSelected(true);
        rojobox.setText("Rojo   (R)");
        rojobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoboxActionPerformed(evt);
            }
        });

        verdebox.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        verdebox.setForeground(new java.awt.Color(255, 255, 255));
        verdebox.setSelected(true);
        verdebox.setText("Verde (G)");
        verdebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeboxActionPerformed(evt);
            }
        });

        azulbox.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        azulbox.setForeground(new java.awt.Color(255, 255, 255));
        azulbox.setSelected(true);
        azulbox.setText("Azul    (B)");
        azulbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulboxActionPerformed(evt);
            }
        });

        todos.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        todos.setForeground(new java.awt.Color(255, 255, 255));
        todos.setSelected(true);
        todos.setText("Todos (RGB)");
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });

        textcanales.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        textcanales.setForeground(new java.awt.Color(255, 255, 255));
        textcanales.setText("Canales de colores");

        textposicion.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        textposicion.setForeground(new java.awt.Color(255, 255, 255));
        textposicion.setText("Mover logo");

        grupoposicion.add(inferiorderecha);
        inferiorderecha.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        inferiorderecha.setForeground(new java.awt.Color(255, 255, 255));
        inferiorderecha.setText("Inferior derecha");
        inferiorderecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inferiorderechaActionPerformed(evt);
            }
        });

        grupoposicion.add(inferiorizquierda);
        inferiorizquierda.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        inferiorizquierda.setForeground(new java.awt.Color(255, 255, 255));
        inferiorizquierda.setText("Inferior izquierda");
        inferiorizquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inferiorizquierdaActionPerformed(evt);
            }
        });

        grupoposicion.add(superiorizquierda);
        superiorizquierda.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        superiorizquierda.setForeground(new java.awt.Color(255, 255, 255));
        superiorizquierda.setText("Superior izquierda");
        superiorizquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superiorizquierdaActionPerformed(evt);
            }
        });

        grupoposicion.add(superiorderecha);
        superiorderecha.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        superiorderecha.setForeground(new java.awt.Color(255, 255, 255));
        superiorderecha.setSelected(true);
        superiorderecha.setText("Superior derecha");
        superiorderecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superiorderechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textcanales)
                            .addComponent(textposicion)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(todos)
                                    .addComponent(azulbox)
                                    .addComponent(verdebox)
                                    .addComponent(rojobox)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(superiorizquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(superiorderecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inferiorizquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inferiorderecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(textcanales)
                .addGap(18, 18, 18)
                .addComponent(rojobox)
                .addGap(11, 11, 11)
                .addComponent(verdebox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(azulbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textposicion)
                .addGap(24, 24, 24)
                .addComponent(superiorderecha)
                .addGap(18, 18, 18)
                .addComponent(superiorizquierda)
                .addGap(18, 18, 18)
                .addComponent(inferiorizquierda)
                .addGap(18, 18, 18)
                .addComponent(inferiorderecha)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rojoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoboxActionPerformed
        if(!verdebox.isSelected() && !azulbox.isSelected()){
            rojobox.setSelected(true);
        }
        changeFilters();
    }//GEN-LAST:event_rojoboxActionPerformed

    private void verdeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeboxActionPerformed
        if(!rojobox.isSelected() && !azulbox.isSelected()){
            verdebox.setSelected(true);
        }
        changeFilters();
    }//GEN-LAST:event_verdeboxActionPerformed

    private void azulboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulboxActionPerformed
        if(!rojobox.isSelected() && !verdebox.isSelected()){
            azulbox.setSelected(true);
        }
        changeFilters();
    }//GEN-LAST:event_azulboxActionPerformed

    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        changeFilterAll();
    }//GEN-LAST:event_todosActionPerformed

    private void inferiorderechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inferiorderechaActionPerformed
        lienzo1.setPosxLogo(582);
        lienzo1.setPosyLogo(360);
        lienzo1.repaint();
    }//GEN-LAST:event_inferiorderechaActionPerformed

    private void inferiorizquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inferiorizquierdaActionPerformed
        lienzo1.setPosxLogo(-10);
        lienzo1.setPosyLogo(360);
        lienzo1.repaint();
    }//GEN-LAST:event_inferiorizquierdaActionPerformed

    private void superiorizquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superiorizquierdaActionPerformed
        lienzo1.setPosxLogo(-10);
        lienzo1.setPosyLogo(-25);
        lienzo1.repaint();
    }//GEN-LAST:event_superiorizquierdaActionPerformed

    private void superiorderechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superiorderechaActionPerformed
        lienzo1.setPosxLogo(582);
        lienzo1.setPosyLogo(-25);
        lienzo1.repaint();
    }//GEN-LAST:event_superiorderechaActionPerformed
    
    public void changeFilters(){
            if(!rojobox.isSelected()){
                todos.setSelected(false);
                lienzo1.setRed(rojobox.isSelected());
                lienzo1.setGreen(verdebox.isSelected());
                lienzo1.setBlue(azulbox.isSelected());
                lienzo1.repaint();
            }
            if(!verdebox.isSelected()){
                todos.setSelected(false);
                lienzo1.setRed(rojobox.isSelected());
                lienzo1.setGreen(verdebox.isSelected());
                lienzo1.setBlue(azulbox.isSelected());
                lienzo1.repaint();
            }
            if(!azulbox.isSelected()){
                todos.setSelected(false);
                lienzo1.setRed(rojobox.isSelected());
                lienzo1.setGreen(verdebox.isSelected());
                lienzo1.setBlue(azulbox.isSelected());
                lienzo1.repaint();
            }
            if(rojobox.isSelected() && verdebox.isSelected() && azulbox.isSelected()){
                todos.setSelected(true);
                changeFilterAll();
            }
            
        
    }
    public void changeFilterAll(){
        if(todos.isSelected()){
            rojobox.setSelected(true);
            verdebox.setSelected(true);
            azulbox.setSelected(true);
            lienzo1.setRed(rojobox.isSelected());
            lienzo1.setGreen(verdebox.isSelected());
            lienzo1.setBlue(azulbox.isSelected());
            lienzo1.repaint();

        }else{
            rojobox.setSelected(true);
            verdebox.setSelected(false);
            azulbox.setSelected(false);
            lienzo1.setRed(rojobox.isSelected());
            lienzo1.setGreen(verdebox.isSelected());
            lienzo1.setBlue(azulbox.isSelected());
            lienzo1.repaint();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltrosRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltrosRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltrosRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltrosRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiltrosRGB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox azulbox;
    private javax.swing.ButtonGroup grupoposicion;
    private javax.swing.JRadioButton inferiorderecha;
    private javax.swing.JRadioButton inferiorizquierda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.mycompany.practica5_rgb.Lienzo lienzo1;
    private javax.swing.JCheckBox rojobox;
    private javax.swing.JRadioButton superiorderecha;
    private javax.swing.JRadioButton superiorizquierda;
    private javax.swing.JLabel textcanales;
    private javax.swing.JLabel textposicion;
    private javax.swing.JCheckBox todos;
    private javax.swing.JCheckBox verdebox;
    // End of variables declaration//GEN-END:variables
}
